/**
 * Cloud Service Maps
 * 
 * Provides comprehensive service maps for each cloud provider
 * following the Google Cloud 4-Words template pattern
 */

export const GCPServices = {
  compute: [
    "Cloud Functions",
    "App Engine",
    "Cloud Run",
    "Google Kubernetes Engine (GKE)",
    "Compute Engine",
    "Bare Metal Solution",
    "Preemptible VMs",
    "Shielded VMs",
    "Sole-tenant Nodes",
    "VMware Engine",
  ],
  storage: [
    "Cloud Filestore",
    "Cloud Storage",
    "Persistent Disk",
    "Local SSD",
  ],
  database: [
    "Cloud Bigtable",
    "Cloud Firestore",
    "Cloud Memorystore",
    "Cloud Spanner",
    "Cloud SQL",
    "Database Migration Service",
    "Cloud SQL Insights",
  ],
  analytics: [
    "BigQuery",
    "BigQuery BI Engine",
    "BigQuery ML",
    "BigQuery GIS",
    "BigQuery Data Transfer Service",
    "Connected Sheets",
    "Cloud Composer",
    "Cloud Data Fusion",
    "Dataflow",
    "Dataprep by Trifacta",
    "Dataproc",
    "Datastream",
    "Pub/Sub",
    "Data Catalog",
    "Google Data Studio",
    "Looker",
    "Public Datasets",
    "Google Earth Engine",
  ],
  "ai-ml": [
    "Vertex AI",
    "AutoML",
    "Vertex AI Data Labeling",
    "Deep Learning VM Images",
    "Vertex AI Workbench",
    "Deep Learning Containers",
    "Vertex AI Matching Engine",
    "Vertex AI Pipelines",
    "Vertex AI Predictions",
    "Vertex AI Training",
    "Vertex AI Edge Manager",
    "Vertex Explainable AI",
    "Vertex AI Feature Store",
    "Vertex ML Metadata",
    "Vertex AI Model Monitoring",
    "Vertex AI Tensorboard",
    "Vertex AI Vizier",
    "Speech-to-Text",
    "Talent Solutions",
    "Text-to-Speech",
    "Cloud TPU",
    "Cloud Translation",
    "Cloud Video Intelligence API",
    "Cloud Vision",
    "Contact Center AI",
    "Dialogflow",
    "Document AI",
    "Recommendations AI",
    "Vision Product Search",
  ],
  networking: [
    "Carrier Peering",
    "Direct Peering",
    "Dedicated Interconnect",
    "Partner Interconnect",
    "Google Cloud Armor",
    "Cloud CDN",
    "Cloud DNS",
    "Cloud Load Balancing",
    "Cloud NAT",
    "Cloud Router",
    "Cloud VPN",
    "Network Service Tiers",
    "Network Telemetry",
    "Traffic Director",
    "Anthos Service Mesh",
    "Virtual Private Cloud",
    "Cloud Domains",
    "VPC Service Controls",
    "Network Intelligence Center",
    "Service Directory",
    "Private Service Connect",
    "Network Connectivity Center",
    "Packet Mirroring",
    "Cloud IDS",
  ],
  "data-integration": [
    "Dataflow",
    "Cloud Data Transfer",
    "Database Migration Service",
    "Datastream",
    "Pub/Sub",
    "Cloud Composer",
    "Cloud Data Fusion",
  ],
};

export const AWSServices = {
  compute: [
    "EC2",
    "Lambda",
    "ECS",
    "EKS",
    "Elastic Beanstalk",
    "Auto Scaling",
    "Lightsail",
    "App Runner",
    "Batch",
    "Outposts",
    "VMware Cloud on AWS",
    "AWS Wavelength",
  ],
  storage: [
    "S3",
    "EBS",
    "EFS",
    "Glacier",
    "Storage Gateway",
    "AWS Backup",
    "AWS DataSync",
    "FSx for Windows",
    "FSx for Lustre",
    "AWS Snow Family",
  ],
  database: [
    "RDS",
    "DynamoDB",
    "ElastiCache",
    "Aurora",
    "DocumentDB",
    "Neptune",
    "Amazon QLDB",
    "Timestream",
    "Redshift",
    "DMS (Database Migration Service)",
  ],
  analytics: [
    "Redshift",
    "Athena",
    "EMR",
    "Kinesis Data Streams",
    "Kinesis Data Firehose",
    "Kinesis Video Streams",
    "Glue",
    "Lake Formation",
    "QuickSight",
    "DataBrew",
    "Lookout for Vision",
    "SageMaker Data Wrangler",
  ],
  "ai-ml": [
    "SageMaker",
    "SageMaker Studio",
    "SageMaker Pipelines",
    "SageMaker Feature Store",
    "SageMaker Model Registry",
    "SageMaker Debugger",
    "SageMaker Monitoring",
    "Rekognition",
    "Comprehend",
    "Polly",
    "Lex",
    "Translate",
    "Forecast",
    "Lookout for Metrics",
    "Lookout for Equipment",
    "Personalize",
    "Textract",
    "Contact Lens for Amazon Connect",
    "Lookout for Vision",
  ],
  networking: [
    "VPC",
    "CloudFront",
    "Route 53",
    "ELB",
    "Application Load Balancer",
    "Network Load Balancer",
    "Direct Connect",
    "VPN",
    "PrivateLink",
    "VPC Peering",
    "AWS Shield",
    "AWS WAF",
    "AWS Firewall Manager",
    "CloudWatch",
    "VPC Flow Logs",
    "Transit Gateway",
    "App Mesh",
  ],
  "data-integration": [
    "AWS DMS",
    "AWS Glue",
    "AWS DataSync",
    "AWS Transfer Family",
    "AWS DataBrew",
    "Amazon Kinesis",
    "Amazon MQ",
    "Amazon AppFlow",
    "AWS Ground Station",
  ],
};

export const AzureServices = {
  compute: [
    "Virtual Machines",
    "App Service",
    "Azure Functions",
    "Container Instances",
    "Kubernetes Service (AKS)",
    "Batch",
    "VM Scale Sets",
    "Service Fabric",
    "Azure Container Apps",
    "Dedicated Hosts",
    "Azure VMware Solution",
    "Azure Spot Virtual Machines",
  ],
  storage: [
    "Blob Storage",
    "Disk Storage",
    "File Share",
    "Table Storage",
    "Archive Storage",
    "Data Lake Storage",
    "Managed Disks",
    "Ultra Disks",
    "NetApp Files",
  ],
  database: [
    "SQL Database",
    "Cosmos DB",
    "Database for MySQL",
    "Database for PostgreSQL",
    "Database for MariaDB",
    "HorizonDB",
    "Redis Cache",
    "Azure SQL Managed Instance",
    "Azure SQL Edge",
    "Azure Database Migration Service",
  ],
  analytics: [
    "Synapse Analytics",
    "Data Factory",
    "Stream Analytics",
    "Databricks",
    "HDInsight",
    "Data Lake Analytics",
    "Power BI",
    "Azure Analysis Services",
    "Data Share",
    "Purview",
  ],
  "ai-ml": [
    "Azure AI Services",
    "Azure Machine Learning",
    "Cognitive Services",
    "Azure OpenAI",
    "Bot Service",
    "Form Recognizer",
    "Azure Search",
    "Computer Vision",
    "Language Understanding",
    "Speech Services",
    "Translator",
    "Anomaly Detector",
    "Content Moderator",
    "Personalizer",
  ],
  networking: [
    "Virtual Network",
    "Load Balancer",
    "Application Gateway",
    "Content Delivery Network",
    "Traffic Manager",
    "ExpressRoute",
    "VPN Gateway",
    "Bastion",
    "Firewall",
    "DDoS Protection",
    "Network Watcher",
    "Front Door",
    "Private Link",
    "Virtual WAN",
  ],
  "data-integration": [
    "Data Factory",
    "Synapse Link",
    "Data Share",
    "Purview",
    "Stream Analytics",
    "Event Hubs",
    "Service Bus",
    "Planetary Computer",
  ],
};

export const OCIServices = {
  compute: [
    "Compute Instances",
    "Container Engine (OKE)",
    "Functions",
    "Bare Metal",
    "VM Database Systems",
    "Dedicated VM Hosts",
    "GPU Instances",
    "Exadata Cloud Service",
  ],
  storage: [
    "Object Storage",
    "Block Storage",
    "File Storage",
    "Archive Storage",
    "Data Transfer Service",
    "Storage Gateway",
  ],
  database: [
    "Autonomous Database",
    "Autonomous Transaction Processing",
    "Autonomous Data Warehouse",
    "MySQL Database",
    "PostgreSQL Database",
    "Data Warehouse",
    "NoSQL Database",
    "Database Migration",
  ],
  analytics: [
    "Big Data Service",
    "Data Integration",
    "Streaming",
    "Data Lake",
    "Analytics Cloud",
    "Hadoop Distribution",
    "Spark Cluster",
  ],
  "ai-ml": [
    "Generative AI Service",
    "Data Science",
    "Machine Learning",
    "Vision AI",
    "Language Processing",
    "Digital Assistant",
    "Anomaly Detection",
  ],
  "data-integration": [
    "GoldenGate",
    "GoldenGate for Big Data",
    "Data Pump",
    "Data Integration Platform",
    "Dataflow",
    "Event Streaming",
    "Service Connector Hub",
  ],
  networking: [
    "Virtual Cloud Network",
    "Internet Gateway",
    "NAT Gateway",
    "Load Balancer",
    "Network Load Balancer",
    "Content Delivery Network",
    "DRG (Dynamic Routing Gateway)",
    "FastConnect",
    "VPN Connect",
    "Service Gateway",
  ],
};

export const IBMServices = {
  compute: [
    "Virtual Servers",
    "Cloud Functions",
    "Code Engine",
    "OpenShift on IBM Cloud",
    "Bare Metal Servers",
    "Hyper Protect Servers",
    "Power Virtual Servers",
  ],
  storage: [
    "Cloud Object Storage",
    "Block Storage",
    "File Storage",
    "Backup & Restore",
    "Cloud Backup",
    "Aspera High-Speed Transfer",
  ],
  database: [
    "Db2",
    "Db2 Warehouse",
    "Cloudant",
    "MongoDB",
    "PostgreSQL",
    "MySQL",
    "Data Warehouse",
    "Db2 Database Recovery",
  ],
  analytics: [
    "Db2 Warehouse",
    "Datastax",
    "Apache Spark",
    "Streaming Analytics",
    "Watson Studio",
    "Planning Analytics",
    "Cognos Analytics",
  ],
  "ai-ml": [
    "Watson AI",
    "Watson Machine Learning",
    "Watson Natural Language Understanding",
    "Watson Computer Vision",
    "Watson Speech to Text",
    "Watson Text to Speech",
    "Watson Assistant",
    "Watson Knowledge Studio",
    "Watson OpenScale",
  ],
  networking: [
    "VPC",
    "Load Balancer",
    "Direct Link",
    "Transit Gateway",
    "CDN",
    "Internet Services",
    "Virtual Private Endpoint",
  ],
  "data-integration": [
    "Db2 Replication",
    "InfoSphere DataStax",
    "Streaming Analytics",
    "Cloud Pak for Data",
    "Event Streams",
    "MQ",
  ],
};

export type CloudProvider = "gcp" | "aws" | "azure" | "oci" | "ibm";
export type ServiceCategory =
  | "compute"
  | "storage"
  | "database"
  | "analytics"
  | "ai-ml"
  | "networking"
  | "data-integration";

export const cloudProviders: { id: CloudProvider; name: string; color: string; icon: string }[] = [
  { id: "gcp", name: "Google Cloud", color: "#4285F4", icon: "☁️" },
  { id: "aws", name: "Amazon Web Services", color: "#FF9900", icon: "📦" },
  { id: "azure", name: "Microsoft Azure", color: "#0078D4", icon: "⬜" },
  { id: "oci", name: "Oracle Cloud", color: "#F80000", icon: "🔴" },
  { id: "ibm", name: "IBM Cloud", color: "#0F62FE", icon: "🔵" },
];

export const getServicesForProvider = (provider: CloudProvider) => {
  const servicesMap = {
    gcp: GCPServices,
    aws: AWSServices,
    azure: AzureServices,
    oci: OCIServices,
    ibm: IBMServices,
  };
  return servicesMap[provider];
};

export const getCategoryColor = (category: ServiceCategory): string => {
  const colors: Record<ServiceCategory, string> = {
    compute: "#FF6B6B",
    storage: "#4ECDC4",
    database: "#45B7D1",
    analytics: "#FFA07A",
    "ai-ml": "#98D8C8",
    networking: "#F7DC6F",
    "data-integration": "#BB8FCE",
  };
  return colors[category] || "#95E1D3";
};
